### ISSUE TITLE
Async version of API

### ISSUE THREAD

**Issue by D219** [alessandro-pezzato/omxdirector#9]
It would help if API command like getStatus(), isLoaded(), isPlaying... had a async version. I'll see if I can add them myself, but I don t know when I ll have the time to try.

**Comment by alessandro-pezzato** [comment]
why do you need an async version? the involved informations are already
available when you request them and don't need any IO operation.

Il giorno Lun 9 Mar 2015 10:19 Rigaud Jeremy <notifications@github.com> ha
scritto:

**Comment by D219** [comment]
As a matter of fact, I don t know why I asked for thoses function to be async, since I didn t had any problem with them. But for play/stop command, it may be useful:

omx.once('stop', function () {
    omx.once('play', function () {
        //Whatever
    });
    omx.play(videos);
});
omx.stop();

Could then be replaced by something as:

omx.stop(function () {
    omx.play(function () {
        //Whatever
    });
});

But it itself can lead to callback hell...

(Next time, I shall think before posting)

**Comment by alessandro-pezzato** [comment]
If you want to play something when the current video has stopped, you
should listen to the `stop` event. Same for the `play` event.

Maybe a queue approach is better, if you simply want to add a video to the
playlist.

Il giorno Lun 9 Mar 2015 16:35 Rigaud Jeremy <notifications@github.com> ha
scritto:

As a matter of fact, I don t know why I asked for thoses function to be

**Comment by D219** [comment]
My use case is to change playlist when some conditions are reached, the playlist always loop.

Exemples:
```javascript
var videos1 = ['1.mp4', '2.mp4'],
      videos2 = ['3.mp4', '4.mp4'];

omx.play(video1, {loop: true});
//[When need of change] 
{
    omx.once('stop', function () {
        omx.once('play', function () {});
        omx.play(videos2, {loop: true});
    });
    omx.stop();
}
```

And I don t use event a lot, so when I switched to omxdirector, it troubled me. Now, it's more style prefference than real need, and everything work.
